apiVersion: v1
kind: Pod
metadata:
  labels:
    run: business
  name: business
spec:
  volumes:
  - name: log-volume
    emptyDir: {}
  containers:
  - image: adityapratapbhuyan/kube-business-ms:distributed
    name: business
    volumeMounts:
      - name: log-volume
        mountPath: "/var/tmp/"
    env:
    - name: spring.jpa.hibernate.ddl-auto
      value: "update"
    - name: management.endpoint.health.show-details
      value: "always"
    - name: management.endpoints.web.exposure.include
      value: "*"
    - name: logging.file.name
      value: "/var/tmp/kube-business-workshop.log"
    ports:
    - containerPort: 8081
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
