apiVersion: v1
kind: Pod
metadata:
  labels:
    run: category
  name: category
spec:
  volumes:
    - name: log-volume
      emptyDir: {}
  containers:
  - image: adityapratapbhuyan/kube-category-ms:distributed
    name: category
    volumeMounts:
    - name: log-volume
      mountPath: "/var/tmp/"
    env:
    - name: spring.jpa.hibernate.ddl-auto
      value: "update"
    - name: management.endpoint.health.show-details
      value: "always"
    - name: management.endpoints.web.exposure.include
      value: "*"
    - name: logging.file.name
      value: "/var/tmp/kube-category-workshop.log"
    ports:
    - containerPort: 8082
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
